//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaktus_Vistavka
    {
        public int Id_kaktus_vistavka { get; set; }
        public Nullable<int> Id_kaktus { get; set; }
        public Nullable<int> Id_vistavka { get; set; }
        public Nullable<int> kolichestvo { get; set; }
    
        public virtual Kaktus Kaktus { get; set; }
        public virtual Vistavka Vistavka { get; set; }
    }
}
