//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vistavka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vistavka()
        {
            this.Kaktus_Vistavka = new HashSet<Kaktus_Vistavka>();
        }
    
        public int Id_vistavki { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Mesto { get; set; }
        public string Nagradi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaktus_Vistavka> Kaktus_Vistavka { get; set; }
    }
}
