//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaktus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kaktus()
        {
            this.Kaktus_Vistavka = new HashSet<Kaktus_Vistavka>();
        }
    
        public int Id_kaktus { get; set; }
        public string Vid { get; set; }
        public string Proishojdenie { get; set; }
        public Nullable<int> Vozrast { get; set; }
        public Nullable<int> Stoimost { get; set; }
        public string InstrukciaPoUhodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaktus_Vistavka> Kaktus_Vistavka { get; set; }
    }
}
